# Permalinks
#
permalink:           pretty
baseurl:             'http://royts.com'

# Setup
title:               I wanna be a Craftsman.
tagline:             'Thoughts about software engineering. by Roy Tsabari'
description:         'royts.com'
url:                 http://royts.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Roy Tsabari
  url:               http://royts.com
  email:             roy@royts.com

# Custom vars
version:             1.0.0

theme: jekyll-theme-hacker
