# Permalinks
#
permalink:           pretty
baseurl: "http://royts.com"

# Setup
title:               I wanna be a Craftsman.
tagline:             'Thoughts about software engineering. by Roy Tsabari'
description:         'royts.com'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

theme: jekyll-theme-hacker
