# Permalinks
#
permalink:           pretty

# Setup
title:               'I wanna be a Craftsman.'
tagline:             'Thoughts about software engineering. by Roy Tsabari'
description:         '_'
url:                 http://royts.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Roy Tsabari
  url:               https://twitter.com/royts
  email:             roy@royts.com

# Custom vars
version:             1.0.0

theme: jekyll-theme-hacker
